### ISSUE TITLE
Hyperparameters detail

### ISSUE THREAD

**Issue by a7b23** [VincentYu68/policy_transfer#1]
The paper mentions that the PPO was run for 500 iterations, with each iteration sampling 40,000 steps from the environment.
Does it mean that run_ppo.py has to be run with a batch size of 40000 and max_step of 2e7 ?

**Comment by VincentYu68** [comment]
The batch size can be flexible, I have tried 20k per iteration and the performance seems similar. The max_step was chosen to be large enough so that the training in source environment converges. For most tasks 2e7 steps is sufficient, though a smaller number could also work.
