### ISSUE TITLE
Walker param manager erroneous

### ISSUE THREAD

**Issue by nisargss97** [VincentYu68/policy_transfer#2]
After setting simulator parameters using _set_simulator_parameter_, _get_simulator_parameter_ does not return the expected values.
This might be due to a logical error in the code in the file _parameter_managers.py, class walker2dParamManager._
The _set_simulator_parameter_
```       
for jid in range(7, 13):<br/>
            if jid in self.controllable_param:
                damp = x[cur_id] * (self.damping_range[1] - self.damping_range[0]) +self.damping_range[0]
                self.simulator.robot_skeleton.joints[jid - 5].set_damping_coefficient(0, damp)
```
updates _joints[2]_ to _joints[7]_
Whereas the _get_simulator_parameter_ 
```         
for jid in range(3, 9):
            cur_damp = self.simulator.robot_skeleton.joints[jid].damping_coefficient(0)
```
returns _joints[3]_ to _joints[8]._

Could you please rectify this? 

Also, what are the 8 controllable simulator parameters did you control to obtain the results in the paper?

**Comment by VincentYu68** [comment]
Thank you for spotting the error! It has been fixed now.

We used the joint dampings, ground friction, and restitution as the randomized simulator parameters for the walker2d example.
